=== alxjrvs/salvageunion-reference/schemas/chassis.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "name": {
        "type": "string"
      },
      "source": { "$ref": "shared/enums.schema.json#/definitions/source" },
      "stats": { "$ref": "shared/objects.schema.json#/definitions/stats" },
      "chassis_abilities": {
        "type": "array",
        "items": {
          "$ref": "shared/objects.schema.json#/definitions/action"
        }
      },
      "description": {
        "type": "string"
      },
      "patterns": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "legalStarting": {
              "type": "boolean"
            },
            "systems": {
              "type": "array",
              "items": { "type": "string" }
            },
            "modules": {
              "type": "array",
              "items": { "type": "string" }
            },
            "drone": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "systems": {
                  "type": "array",
                  "items": { "type": "string" }
                },
                "modules": {
                  "type": "array",
                  "items": { "type": "string" }
                }
              }
            }
          }
        }
      },
      "page": { "type": "number" }
    }
  }
}

=== alxjrvs/salvageunion-reference/data/keywords.json
[
  {
    "source": "core",
    "name": "abilities",
    "description": "Refers to Pilot, Mech, and NPC Abilities such as those Bio-Titans have. Often activated by spending Ability Points or Energy Points respectively to produce a variety of effects in play. Pilot Abilities may be used in a Mech unless otherwise stated.",
    "page": 321
  },
  {
    "source": "core",
    "name": "ability points",
    "description": "Each Pilot has a number of Ability Points which they can use to trigger their Abilities in play. Ability Points restore fully after 1 week of rest during Downtime.",
    "page": 321
  },
  {
    "source": "core",
    "name": "action scene",
    "description": "Refers to any action packed situation in the game such as combat or chases where time is measured in Turns lasting roughly a minute each.",
    "page": 321
  },
  {
    "source": "core",
    "name": "advanced abilities",
    "description": "Refers to both the Advanced Class and Hybrid Abilities. Trained with 2 Training Points during Downtime.",
    "page": 321
  },
  {
    "source": "core",
    "name": "advanced tree",
    "description": "A Pilot that has specialised in their Core Class can take Abilities from the Advanced Tree of that Class. A Pilot can advance into their Advance Tree once they have taken 6 Core Abilities including all 3 Abilities linked to their Advanced Tree. For example the Engineer must take all 3 Abilities in the Mech-Tech tree before advancing into the Advanced Engineer Tree. Once they have chosen to advance into their Advanced Tree they can no longer choose to advance into either of their Hybrid Class options. They may still take all Abilities from their Core Class, such as the Engineer Abilities if they were an Engineer.",
    "page": 321
  },
  {
    "source": "core",
    "name": "bio-titan",
    "description": "Gigantic and terrifying mutated organisms formed of an amalgamation of mechanised flesh. They have a bizarre range of powers and adaptations that make them incredibly powerful foes to encounter. They can be salvaged for vast amounts of Bio-Titan Salvage when slain which can be sold as Tech 1 Scrap.",
    "page": 321
  },
  {
    "source": "core",
    "name": "blind",
    "description": "If someone is Blind, they gain the Vulnerable Trait and cannot take any actions that would require sight unless they find another means to circumvent this.",
    "page": 321
  },
  {
    "source": "core",
    "name": "core abilities",
    "description": "The main Abilities that the 6 Core Classes gain access to. Trained with 1 Training Point during Downtime.",
    "page": 321
  },
  {
    "source": "core",
    "name": "core class",
    "description": "The 6 Core Pilot Classes of Salvage Union. Players play as one of these. Engineer, Hacker, Hauler, Salvager, Scout, Soldier.",
    "page": 322
  },
  {
    "source": "core",
    "name": "corpo",
    "description": "The enemy. Refers both to the exploitative corporations who hold most of the power in the world and individuals who belong to or work for a Corpo.",
    "page": 322
  },
  {
    "source": "core",
    "name": "creature",
    "description": "Broadly covers all people, animals, mutants and cyborgs in the game. Does not include Bio-Titans or Meld.",
    "page": 322
  },
  {
    "source": "core",
    "name": "damaged",
    "description": "If a System, Module, or Chassis is damaged it is inoperable and cannot be used in any way until repaired and restored to the Intact Condition.",
    "page": 322
  },
  {
    "source": "core",
    "name": "death blow",
    "description": "A special type of attack made against a target in Close Range that is on 0 SP or HP or is otherwise incapacitated that kills or destroys them entirely.",
    "page": 322
  },
  {
    "source": "core",
    "name": "destroyed",
    "description": "A destroyed System, Module, Chassis, or Vehicle is entirely inoperable. It cannot be repaired, salvaged, scrapped, or used in any way.",
    "page": 322
  },
  {
    "source": "core",
    "name": "difficult terrain",
    "description": "Any type of terrain that would be difficult to cross such as mountainous and hilly terrain, heavy swamp, or a thick forest. Movement over long distances through Difficult Terrain takes 2× as long. This does not apply in combat and action scenes though the Mediator may apply other penalties as appropriate.",
    "page": 322
  },
  {
    "source": "core",
    "name": "downtime",
    "description": "A period of one week, typically spent on a Union Crawler. Used to restore all Mech and Pilot statistics, train new Abilities, craft and repair Mechs and move across the wasteland via the Crawler.",
    "page": 322
  },
  {
    "source": "core",
    "name": "downtime action",
    "description": "Actions that you can perform during your week of Downtime. Typically in your Union Crawler.",
    "page": 322
  },
  {
    "source": "core",
    "name": "drone",
    "description": "Refers to all remotely controlled or automated mechanical Drones. Treat Drones as Mechs for the purpose of the rules and Abilities.",
    "page": 322
  },
  {
    "source": "core",
    "name": "energy points",
    "description": "Each Mech has an Energy Point value representing the output of its reactor. These are spent to activate a wide range of Abilities. Energy Points restore fully after 1 week of Downtime in a Mech Bay of the Tech Level of the Mech or higher.",
    "page": 322
  },
  {
    "source": "core",
    "name": "environmental effects",
    "description": "Environmental effects include heat and cold, heavy rain, radiation storms, high winds and flooding. These can cause a variety of negative effects in play as decided by the Mediator.",
    "page": 322
  },
  {
    "source": "core",
    "name": "free action",
    "description": "A simple action like talking which does not take up much time in a round and can be done for free.",
    "page": 322
  },
  {
    "source": "core",
    "name": "group",
    "description": "The Pilots and their Mechs count as a group and will often be referred to as such. Any allied group counts as a group as well. During Group Initiative, play switches between different groups.",
    "page": 322
  },
  {
    "source": "core",
    "name": "heat",
    "description": "Generates on your Mech when you perform various tasks. When you reach your Heat Capacity you must make a Heat Check. If you start your turn at your Heat Capacity you must also make a Heat Check.",
    "page": 322
  },
  {
    "source": "core",
    "name": "heat check",
    "description": "To make a Heat Check you roll a d20. If the result is equal to or under your current Heat you must roll on the Reactor Overload Table. A roll of a 20 is always a success, as your Heat Capacity can be higher than 20.",
    "page": 322
  },
  {
    "source": "core",
    "name": "hit points",
    "description": "How resilient your Pilot, a creature, or a person is. When your Pilot is reduced to 0 HP they must roll on the Critical Injury Table. NPCs typically die at 0 HP. Any attack that deals SP damage deals 2× that amount to anything that has a Hit Point value.",
    "page": 323
  },
  {
    "source": "core",
    "name": "hybrid classes",
    "description": "A Pilot that has specialised in multiple roles. A Pilot can advance into a Hybrid Class once they have taken 6 Core Abilities, including all 3 Abilities linked to the Hybrid Class they have chosen. For example the Engineer must take all 3 Abilities in the Forging Tree before advancing into the Fabricator Class. Once a Pilot has chosen their Hybrid Class they cannot advance into any other Hybrid Class or Advanced Tree. They also can no longer choose Abilities from their Core Class that their Hybrid Class cannot learn. For example if the Engineer advances into the Fabricator Class they cannot take any Abilities from the Mech-Tech Tree, though they can retain any Abilities they have previously picked from that tree.",
    "page": 323
  },
  {
    "source": "core",
    "name": "incapacitated",
    "description": "If a creature is incapacitated it is unconscious and typically on 0 HP. A death blow can be performed upon an incapacitated creature.",
    "page": 323
  },
  {
    "source": "core",
    "name": "inoperable",
    "description": "If a System, Module, Chassis, Vehicle, or Pilot Equipment is inoperable it cannot be used in any way. Mechs and Vehicles cannot be piloted, weapons cannot be used to make attacks, and no Abilities can be activated. This typically applies when damaged, but some effects will also make things inoperable.",
    "page": 323
  },
  {
    "source": "core",
    "name": "intact",
    "description": "If a System, Module, Chassis, Vehicle, or Pilot Equipment has the Intact Condition, it is in full working order and can be used normally.",
    "page": 323
  },
  {
    "source": "core",
    "name": "integrated",
    "description": "If a System or Module is integrated into a Mech Chassis it comes as part of it. It does not take up any additional System or Module Slots and cannot be removed, replaced or fitted on another Mech. It can still be targeted with any Ability that would target a System or Module. If damaged or destroyed it can be repaired or restored by any effect that would Repair the Chassis. Use the Tech Level and Salvage Value of the Chassis for any such Abilities.",
    "page": 323
  },
  {
    "source": "core",
    "name": "irradiated",
